name: Greeting from Yilei
on: push
jobs:
  my-job:
  name: My Job
  runs-on: ubuntu-latest
  steps:
  - name: Print a greeting
    env:
      MY_VAR: Hi there! My name is
      FIRST_NAME: Yilei
      MIDDLE_NAME: The
      LAST_NAME: JIANG
    run: |
      echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
